### ISSUE TITLE
feat: center around active tab

### ISSUE THREAD

**Issue by aaronclimbs** [edvardxyz/Tabs-in-title#1]
Would it be possible to add an option to center the tab bar around the active tab? I have limited space on my top bar and would like to only see a few tabs around the current active tab, rather than just the first five or ten.

![2021-05-12_13 03 36](https://user-images.githubusercontent.com/10203370/118015640-82d21c80-b322-11eb-8d0a-8f5df46edc23.png)

**Comment by edvardxyz** [comment]
Did you change the amount of characters inside preferences?
And maybe remove the spaces around the tab seperator for more space.
But I like your idea, maybe i will look into something like that.

**Comment by aaronclimbs** [comment]
I did mess around with the spacing and the character max, but it seems like that wouldn't be a consistent fix as would still be dependent on the number of tabs open. I can see if I can put a PR together if I figure out a fix.

**Comment by edvardxyz** [comment]
I think this might work havent tested.
Just have to active this when more than some number of tabs are present.
it also need to do some check when activeTab.index-TABS_SHOW_AROUND < 0
also need to truncate title

`TABS_SHOW_AROUND = 2;
function aroundTabs(){
    getCurrentWindowTabActive().then((activeTab) => {
        getCurrentWindowTabs().then((tabs) => {
            let tabsList = '';
            for (let tab of tabs){
                if(tab.index >= activeTab-TABS_SHOW_AROUND && tab.index <= activeTab.index+TABS_SHOW_AROUND){
                    if(tab.active){
                        tabsList += `|| >>${tab.title}<< `;
                        continue;
                    }
                    tabsList += `|| ${tab.title} `;
                }
            }
            changeTitleWindow(tabs[0].windowId, tabsList);
        });
    });
}
`

**Comment by edvardxyz** [comment]
I think this might work havent tested.
Just have to active this when more than some number of tabs are present.
~~it also need to do some check when activeTab.index-TABS_SHOW_AROUND < 0~~
It needs to add extra tabs on the oppesite side if your active tab is on the edges.
also need to truncate title

```
TABS_SHOW_AROUND = 2;
function aroundTabs(){
    getCurrentWindowTabActive().then((activeTab) => {
        getCurrentWindowTabs().then((tabs) => {
            let tabsList = '';
            for (let tab of tabs){
                if(tab.index >= activeTab[0].index-TABS_SHOW_AROUND && tab.index <= activeTab[0].index+TABS_SHOW_AROUND){
                    if(tab.active){
                        tabsList += `|| >>${tab.title}<<` ;
                        continue;
                    }
                    tabsList += `|| ${tab.title}` ;
                }
            }
            changeTitleWindow(tabs[0].windowId, tabsList);
        });
    });
}
```

**Comment by edvardxyz** [comment]
```
function getCurrentWindowTabActive(){
    return browser.tabs.query({currentWindow: true, active: true});
}

```

**Comment by edvardxyz** [comment]
@aaronclimbs I see you forked, but i added a cycle mode you can enable in settings.
If you are working on it I would like to see how you would do it.
